DELETE FROM PLANT WHERE plantID < 0;
INSERT INTO plant (name, description, is_Invasive, is_Native, color, image_FruitURL, image_LeafURL, image_Fruit_Source, image_Leaf_Source, wiki_Link, plantID) VALUES ('Red Raspberry', 'Rubus idaeus, commonly known as raspberries, are perennial plants with biennial stems that grow from a perennial root system. These plants produce edible red aggregate fruits consisting of numerous drupelets around a central core, with distinct growth patterns in their first and second years.', false, true, 'Red', 'static/plantImages/RaspberriesF.jpg', 'static/plantImages/RaspberriesL', 'By Ivar Leidus - Own work, CC BY-SA 4.0, https://commons.wikimedia.org/w/index.php?curid=96641162', 'By Tomwsulcer - Own work, CC0, https://commons.wikimedia.org/w/index.php?curid=19087683', 'https://en.wikipedia.org/wiki/Rubus_idaeus', -2);



INSERT INTO plant (name, description, is_Invasive, is_Native, color, image_FruitURL, image_LeafURL, image_Fruit_Source, image_Leaf_Source, wiki_Link, plantID) VALUES ('New Jersey Tea', 'Ceanothus Americanus, a shrub reaching 18-42 inches (0.5-1m) in height, with thin branches and extensive root systems adapted to wildfires. It features clumps of white flowers on long peduncles and produces dry, dehiscent seed capsules.'false, true, 'White', 'static/plantImages/Ceanothus-americanus.jpg', 'src/main/resources/static/plantImages/Ceanothus-americanus-leaf.jpg', missing 2 sources, 'https://en.wikipedia.org/w/index.php?title=Ceanothus_americanus&oldid=1157315821', -3); 

INSERT INTO plant (name, description, is_Invasive, is_Native, color, image_FruitURL, image_LeafURL, image_Fruit_Source, image_Leaf_Source, wiki_Link, plantID) VALUES ('Gray dogwood', 'Cornus Racemosa, a shrub reaching 1.2-3 m (4-10 ft) in height, forming thickets through underground rhizomes. It bears small white flowers in rounded clusters, followed by white fruits, attracting various bird species. The plant'/'s gray bark, oppositely arranged leaves, and reddish or purplish fall foliage contribute to its appearance.' false, true, 'White', )

INSERT INTO plant (name, description, is_Invasive, is_Native, color, image_FruitURL, image_LeafURL, image_Fruit_Source, image_Leaf_Source, wiki_Link, plantID) VALUES ('American hazelnut, American filbert', 'Corylus americana, is a medium to large shrub, growing 2.5-5 m (8-16 ft) tall with a spreading crown. It blooms in early to mid-spring, featuring hanging male catkins and clusters of tiny female flowers. It produces edible nuts enclosed in leaf-like bracts that mature from July to October.' false, true, 'Brown nut, white stamins, brown catins', )

INSERT INTO plant (name, description, is_Invasive, is_Native, color, image_FruitURL, image_LeafURL, image_Fruit_Source, image_Leaf_Source, wiki_Link, plantID) VALUES ('Fragrant sumac', 'Rhus aromatica, a deciduous shrub in the Anacardiaceae family, is native to North America, thriving in a range of conditions from southern Canada to the lower 48 states. With a rounded form, it grows 2-5 ft tall and wide, producing small yellow flowers in clusters before its leaves emerge. The plant'/'s three-leaflet leaves, orange-red fall foliage, and lemon-scented crushed leaves make it a distinctive species.' false, true, 'Yellow')


